services:
  api:
    build: .
    container_name: ultimate-rps-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./database.db:/app/database.db

  redis:
    image: redis:7-alpine
    container_name: ultimate-rps-redis
    ports:
      - "6379:6379" 
